List in alphabetical order
jaredpalmer/awesome-react-render-props pull request #67
Opened 2018-06-27 11:08 UTC by thebuilder

This fixes #66
Also align the naming to use kebab case

2018-06-27 13:13 UTC, ctrlplusb requested changes
Thanks for getting this going @thebuilder - it definitely helps to have them sorted. 

I've noted a few places where the items were out of order.

A couple of comments from my side:
 
 - The whole "react-" prefix on libs throws me off a bit. I feel like it devalues the alphabetical ordering a bit. Not sure what to do here, just a note.
 - Should we consider moving scoped packages to the top of the lists? Seemed a bit strange having to read past the scoping, but maybe that is just me.

2018-06-27 13:13 UTC, ctrlplusb commented on README.md
> +- [react-motion](https://github.com/chenglou/react-motion): A spring that solves your animation problems.
Should be above `react-move`

2018-06-27 13:13 UTC, ctrlplusb commented on README.md
> +- [react-google-maps-loader](https://github.com/xuopled/react-google-maps-loader): Simple loader to use google maps services
Should be below `react-google-calendar-events-list`

2018-06-27 13:13 UTC, ctrlplusb commented on README.md
> +- [@danwang/retainer](https://github.com/danwang/retainer): Compose render prop components by lifting computation into containers
Should be below `render-props-compose`

2018-06-27 13:16 UTC, ctrlplusb commented
Side note: I am using your `react-intersection-observer` in a side project of mine. Really dig it, thanks for it! 😀

2018-06-28 08:14 UTC, thebuilder commented
I agree about the `react-` prefix, but removing isn't really an option.
I think it would require rethinking how packages are presented.

### Ideas:
[Google Maps Loader](https://github.com/xuopled/react-google-maps-loader) *(react-google-maps-loader)* -  Simple loader to use google maps services
**Google Maps Loader** - [react-google-maps-loader](https://github.com/xuopled/react-google-maps-loader):  Simple loader to use google maps services

#### Table listing
Name | Package | Description
------------ | -------------  | -------------
Google Maps Loader | [react-google-maps-loader](https://github.com/xuopled/react-google-maps-loader)  | Simple loader to use google maps services

2018-06-28 16:12 UTC, ctrlplusb commented
Name column is an interesting proposal, but not sure if it will always work. "Motion" vs "React Motion" for example. "React" is really a part of that libs name.  Maybe we just stick with as is for now and track this proposal separately.

2018-06-28 16:26 UTC, kentcdodds commented
Yeah, I think the name column idea will be redundant most of the time. Also, going with a table layout will make this harder to contribute to, so let's just stick with the list.

2018-06-28 16:32 UTC, thebuilder commented
Agreed.

2018-06-29 11:46 UTC, ctrlplusb approved these changes

2018-06-29 13:24 UTC, merged

2018-06-29 19:41 UTC, jaredpalmer commented
While i like the visuals on the table, my only issue with a is that they can be very hard to edit on GitHub's online editor, making contribution a tougher.